### ISSUE TITLE
Prime Factorization Bug.

### ISSUE THREAD

**Issue by AlFahimBinFaruk** [ShahjalalShohag/code-library#16]
In Number theory dir prime factorization code snippet has a bug i guess its giving this = error: '__uint128_t' does not name a type. dir link(https://github.com/ShahjalalShohag/code-library/blob/master/Number%20Theory/Prime%20Factorization%20Fastest.cpp)

**Comment by st3inum** [comment]
Maybe you are using clang, use g++ instead.

**Comment by AlFahimBinFaruk** [comment]
> Maybe you are using clang, use g++ instead.
I am using the GNU G++.

**Comment by AlFahimBinFaruk** [comment]
> g, use g++ instead.
