### ISSUE TITLE
I want to make a collection of some most useful algorithms  codes at one Place 

### ISSUE THREAD

**Issue by Bharath-KumarReddy** [ShahjalalShohag/code-library#26]
1)K-way merge Algorithm

2)Stack Reduced Quick Sort

3)Merge sort combined with Insertion Sort

4)Prims, Topological, Kruskal's algorithm

5)DijKstra , Floyd Warshall ,bellman ford algorithm

6)Backtracking
a) Rat Maze
b) N-Queen
c) Sudoku
d) Sum of Subset

7)Activity selection , Huffman Encoding

8) Longest common subsequence , Quick Sort etc 

please assign this to me , I am very much Interested to contribute myself in  Hacktoberfest_2023 : )

**Comment by ShahjalalShohag** [comment]
I think we have templates for most of the important topics that you have listed here. Try to improve the existing codes if possible.
