### ISSUE TITLE
Adding Backtracking folder

### ISSUE THREAD

**Issue by Bharath-KumarReddy** [ShahjalalShohag/code-library#28]
I want to create a new folder which includes all Backtracking problems with codes.

Please assign this to me , I am interested to contribute my self in hacktoberfest_23 : )

**Comment by ShahjalalShohag** [comment]
You can add them under the Miscellaneous folder. We need templates for important algorithms, not solutions to specific problems.

**Comment by Bharath-KumarReddy** [comment]
Ok sure : )

**Comment by Bharath-KumarReddy** [comment]
I just now added the backtracking algos in the Miscellaneous folder and I had made a PR #31 
Once please check and merge , kindly inform for further modifications , hacktoberfest_23 : )
