### ISSUE TITLE
Dijkstra algorithm 

### ISSUE THREAD

**Issue by Yash9276** [ShahjalalShohag/code-library#37]
Hey 👋 , I want to add dijkstra algorithm to this repo which useful for finding shortest path from source to destination.  Please assign it to me under Hacktoberfest tag
Thank you:)

**Comment by Varun-Gupta-Dev** [comment]
Hello, I can add Dijkstras Algorithm to this repo. I have done dedicated course of DSA and solved 300+ questions during the course and therefore can contribute effectively on this issue.

**Comment by nrhitik** [comment]
I would like to work on this issue. please assign me this issue.

**Comment by ShahjalalShohag** [comment]
We already have it: https://github.com/ShahjalalShohag/code-library/blob/main/Graph%20Theory/Dijkstra.cpp
